todo_p/tasks_a/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', view=views.home, name='home'),
    path('login/', view=views.LoginInterfaceView.as_view(), name= 'login'),
    path('signup/', view=views.SignUpView.as_view(), name='signup'),
    path('logout/', view=views.logout_view, name='logout'),
    path('task/<int:pk>/delete/', view=views.TaskDeleteView.as_view(), name='task-delete'),
    path('task/<int:pk>/update/', view=views.TaskUpdateView.as_view(), name='task-update'),
    path('task/create/', view=views.TaskCreateView.as_view(), name='task-create')
]

todo_p/todo_p/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks_a.urls'))
]

todo_p/tasks_a/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

todo_p/tasks_a/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Todo

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=35, required=False)

    class Meta:
        model = User
        fields = ['first_name','username', 'password1', 'password2']

    def save(self, commit = True):
        user = super(SignUpForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']

        if commit:
            user.save()
        return user

class TaskCreateForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'completed']

todo_p/tasks_a/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.models import User
from django.contrib.auth import logout
from .forms import SignUpForm,TaskCreateForm
from django.contrib.auth.decorators import login_required
from .models import Todo

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# Create your views here.
@login_required(login_url='login')
def home(request):
    todos = Todo.objects.all()
    paginator = Paginator(todos, 5)

    page = request.GET.get('page')

    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)

    context = {
        'todos': objects,
    }
    return render(request, 'tasks_a/test.html', context=context)

class LoginInterfaceView(LoginView):
    template_name = 'tasks_a/login_form.html'
    success_url = '/'

class SignUpView(CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'tasks_a/signup_form.html'
    success_url = '/'

def logout_view(request):
    logout(request)
    return redirect('login')

class TaskDeleteView(DeleteView):
    model = Todo
    template_name = 'tasks_a/task_confirm_delete.html'
    success_url = '/'

class TaskUpdateView(UpdateView):
    model = Todo
    fields = ['title', 'completed']
    template_name = 'tasks_a/task_form.html'
    success_url = '/'

class TaskCreateView(CreateView):
    model = Todo
    form_class = TaskCreateForm
    template_name = 'tasks_a/task_create_form.html'
    success_url = '/'

todo_p/tasks_a/templates/tasks_a/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} BASE {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block extra_css %}{% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
        rel="stylesheet">
</head>

<body>
    <nav class="nav-bar">
        <a class="nav-link" href="">ToDo</a>
        {% if user.is_authenticated %}
        <ul class="nav-ul">
            <li class="nav-list"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
        </ul>
        {% else %}
        <ul class="nav-ul">
            <li class="nav-list"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
            <li class="nav-list"><a class="nav-link" href="{% url 'signup' %}">Sign Up</a></li>
        </ul>
        {% endif %}

    </nav>
    <main style="padding: 50px 100px 20px 100px;">
        {% block content %} BASE {% endblock %}
    </main>
</body>

</html>

todo_p/tasks_a/templates/tasks_a/home.html
{% extends 'tasks_a/base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}

<div class="add-todo" style="display: flex; width: 100%;justify-content: space-between;">
    <h1>Welcome <span id="username">{{user.username}}!</span></h1>
    <button
        style="height: 25px; border: none; box-shadow: rgba(0, 0, 0, 0.05) 0px 0px 0px 1.5px; background-color: white; padding: 10px; display: flex; align-items: center; cursor: pointer;">+
        Add ToDo</button>
</div>


{% for todo in todos %}
<ul>
    <li
        style="width: 100%; background-color: white; margin-bottom: 25px; list-style: none; display: flex; align-items: center; justify-content: space-between; flex-direction: row; border-radius: 10px; padding: 10px;">
        <div>
            <p style="margin-bottom: 5px;"><strong>{{todo.title}}</strong></p>
            <p>Completed:
                {{todo.completed|yesno:"Yes,No"}}</p>
        </div>

        <div>
            <a href=""><img src="{% static 'images/edit_icon.png' %}" alt="" height="20px"
                    style="margin-right: 20px;"></a>
            <a href=""><img src="{% static 'images/delete_icon.png' %}" alt="" height="20px"></a>
        </div>

    </li>
</ul>

{% empty %}
<p>No todos found add now</p>
<img src="{% static 'images/empty-todo.png' %}" alt="empty-todo">
{% endfor %}

{% endblock %}

todo_p/tasks_a/templates/tasks_a/login_form.html
{% extends 'tasks_a/base.html' %}
{% load static %}

{% block title %} Home {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/login_form.css' %}">
{% endblock %}


{% block content %}

<div class="form-div" style="background-color: transparent;">
    <form action="" method="post">
        {% csrf_token %}
        <h3>User Login</h3>
        <p class="tell">Enter your details here</p>

        {{ form.non_field_errors }}
        <!-- for username -->
        <div class="form-group">
            <input type="text" name="{{ form.username.name }}" id="id_username" placeholder="Username">

            {{ form.username.errors }}
        </div>

        <!-- for password -->
        <div class="form-group">
            <input type="password" name="{{ form.password.name }}" id="id_password" placeholder="Password">

            {{ form.password.errors }}
        </div>
        <button type="submit">Sign in</button>
        <p class="toggle-text">Don't have an account?<a href="{% url 'signup' %}" class="toggle-link"
                style="color: rgb(245, 170, 78); margin-left: 5px;">Register Now</a>
        </p>
    </form>
</div>


{% endblock %}

todo_p/tasks_a/templates/tasks_a/signup_form.html
{% extends 'tasks_a/base.html' %}
{% load static %}

{% block title %} Home {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/login_form.css' %}">
{% endblock %}


{% block content %}

<div class="form-div" style="background-color: transparent;">
    <form action="" method="post">
        {% csrf_token %}
        <h3>User SignUp</h3>
        <p class="tell">Enter your details here</p>
        <!-- First Name Field -->
        <div class="form-group">
            <input type="text" name="{{ form.first_name.name }}" id="id_first_name" placeholder="Name">
            {{ form.first_name.errors }}
        </div>


        <!-- Username Field -->
        <div class="form-group">
            <input type="text" name="{{ form.username.name }}" id="id_username" placeholder="Username" required>
            {{ form.username.errors }}
        </div>



        <!-- Password1 Field  -->
        <div class="form-group">
            <input type="password" name="{{ form.password1.name}}" id="id_password1" placeholder="Password">
            {{ form.password1.errors}}
        </div>

        <!-- Confirm Password Field  -->
        <div class="form-group">
            <input type="password" name="{{ form.password2.name}}" id="id_password2" placeholder="Confirm Password">
            {{ form.password2.errors }}
        </div>



        <!-- {{form}} -->
        <button type="submit">Sign up</button>
        <p class="toggle-text">Already have an account?<a href="{% url 'login' %}" class="toggle-link"
                style="color: rgb(245, 170, 78); margin-left: 5px;">Login</a></p>
    </form>
</div>


{% endblock %}

todo_p/tasks_a/templates/tasks_a/task_confirm_delete.html
{% extends 'tasks_a/base.html' %}
{% load static %}

{% block title %} Task Delete {% endblock %}



{% block content %}

<h1>Confirm Deletion</h1>
<p>Are you sure you want to delete <span style="color: red;">"{{ object }}"?</span></p>
<form method="post">{% csrf_token %}
    <button type="submit"
        style="margin-top: 20px; padding: 5px; background-color: tomato; border: none; border-radius: 5px; color: white;">Yes,
        I'm sure</button>
    <a href="{% url 'home' %}"
        style="text-decoration: none; background-color: rgb(97, 97, 97); color: white; padding: 5px; border-radius: 5px; font-size: small;">No,
        take me
        back</a>
</form>

{% endblock %}

todo_p/tasks_a/templates/tasks_a/task_create_form.html
{% extends 'tasks_a/base.html' %}
{% load static %}

{% block title %} Update Task {% endblock %}

{% block content %}

<style>
    #id_title {
        width: 25%;
        margin-bottom: 10px;
    }
</style>

<h1>Create Task</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit"
        style="margin-top: 20px; padding: 5px; background-color: green; border: none; border-radius: 5px; color: white;">CREATE</button>
    <a href="{% url 'home' %}"
        style="text-decoration: none; background-color: rgb(97, 97, 97); color: white; padding: 5px; border-radius: 5px; font-size: small;">No,
        take me
        back</a>
</form>

{% endblock %}

todo_p/tasks_a/templates/tasks_a/task_form.html
{% extends 'tasks_a/base.html' %}
{% load static %}

{% block title %} Update Task {% endblock %}

{% block content %}

<style>
    #id_title {
        width: 25%;
        margin-bottom: 10px;
    }
</style>

<h1>Update Task</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit"
        style="margin-top: 20px; padding: 5px; background-color: green; border: none; border-radius: 5px; color: white;">SAVE</button>
    <a href="{% url 'home' %}"
        style="text-decoration: none; background-color: rgb(97, 97, 97); color: white; padding: 5px; border-radius: 5px; font-size: small;">No,
        take me
        back</a>
</form>

{% endblock %}

todo_p/tasks_a/templates/tasks_a/test.html
{% extends 'tasks_a/base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}

<style>
    .page-link {
        text-decoration: none;
        color: rgb(240, 8, 8);
        margin: 20px 10px;
    }
</style>
<div class="add-todo" style="display: flex; width: 100%;justify-content: space-between;">
    <h1>Welcome <span id="username">{{user.username}}!</span></h1>
    <a href="{% url 'task-create' %}"
        style="height: 25px; border: none; box-shadow: rgba(0, 0, 0, 0.05) 0px 0px 0px 1.5px; background-color: white; padding: 10px; display: flex; align-items: center; cursor: pointer; font-size: small; text-decoration: none;">+
        Add ToDo</a>
</div>


{% for todo in todos %}
<ul style="margin-top: 20px;">
    <li
        style="width: 100%; background-color: white; margin-bottom: 25px; list-style: none; display: flex; align-items: center; justify-content: space-between; flex-direction: row; border-radius: 10px; padding: 10px;">
        <div>
            <p style="margin-bottom: 5px;"><strong>{{todo.title}}</strong></p>
            <p>Completed:
                {{todo.completed|yesno:"Yes,No"}}</p>
        </div>

        <div>
            <a href="{% url 'task-update' todo.pk %}"><img src="{% static 'images/edit_icon.png' %}" alt=""
                    height="20px" style="margin-right: 20px;"></a>
            <a href="{% url 'task-delete' todo.pk %}"><img src="{% static 'images/delete_icon.png' %}" alt=""
                    height="20px"></a>
        </div>

    </li>
</ul>

{% empty %}
<p>No todos found add now</p>
<img src="{% static 'images/empty-todo.png' %}" alt="empty-todo">
{% endfor %}




<div class="pagination">
    <span class="step-links">
        {% if todos.has_previous %}
        <a class="page-link" href="?page=1">&laquo; first</a>
        <a class="page-link" href="?page={{ todos.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ todos.number }} of {{ todos.paginator.num_pages }}.
        </span>

        {% if todos.has_next %}
        <a class="page-link" href="?page={{ todos.next_page_number }}">next</a>
        <a class="page-link" href="?page={{ todos.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock %}